version: '3.3'
services:
    # server
    #===============================================================
    server:
        build: ./server
        ports:
            - "1000:1000"
        command: npm run start:dev
        volumes:
            - "./server/src:/src"
        depends_on:
            - "postgres"
    #===============================================================

    # Postgres
    #===============================================================
    postgres:
        build: ./postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${APP_DB_USERNAME}
            - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
            - POSTGRES_DB=${APP_DB_NAME}
            - PORT=${APP_DB_PORT}
        ports:
            - "5431:${APP_DB_PORT}"
    #===============================================================

volumes:
    postgres_data: